### ISSUE TITLE
Add Fenix recent crashes links

### ISSUE THREAD

**Issue by rvandermeulen** [pascalchevrel/rm_queries#6]
Currently, we have a `Firefox recent crashes (3 days)` link but no equivalent for Fenix. Can we add one? Something like https://crash-stats.mozilla.org/topcrashers/?product=Fenix&version=113.0a1&process_type=any&days=3

**Comment by dsmithpadilla** [comment]
FYI the nightly link is correct but the label shows "Fenix Last Beta crashes" when it should be either referring to nightly or the recent crashes
<img width="251" alt="Screenshot 2023-06-28 at 11 44 41 AM" src="https://github.com/pascalchevrel/rm_queries/assets/88508950/4df674ee-4301-42a4-a332-a354a76e99ab">

**Comment by pascalchevrel** [comment]
fixed in https://github.com/pascalchevrel/rm_queries/commit/3ac5ce95a90ea24ecb79a4a3e32653c35da1964b, thanks
